apiVersion: apps/v1
kind: Deployment
metadata:
  name: dedi-python-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: site-nginx-frontend
  template:
    metadata:
      labels:
        name: site-nginx-frontend
    spec:
      containers:
        - name: blog
          image: brdcookies6969/dedi-python-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: site-python-app-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    name: site-nginx-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-python-app-ingress
  annotations:
    #app.kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: dedi-python-app.brd.my.id
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: site-python-app-service
              port:
                number: 80
